/*
 * ASF include list for mic_test. Based on the autogenerated asf.h from ASF's
 * stdio_usb example (UC3-A3 Xplained), plus the ADC and cycle counter drivers.
 */
#ifndef ASF_H
#define ASF_H

#include <compiler.h>
#include <status_codes.h>
#include <flashc.h>
#include <gpio.h>
#include <board.h>
#include <interrupt.h>
#include <power_clocks_lib.h>
#include <sleep.h>
#include <parts.h>
#include <sleepmgr.h>
#include <uc3/sleepmgr.h>
#include <sysclk.h>
#include <led.h>
#include <usb_protocol_cdc.h>
#include <udi_cdc.h>
#include <stdio_usb.h>
#include <udc.h>
#include <udd.h>
#include <adc.h>
#include <cycle_counter.h>

#endif // ASF_H
